version: "3.9"
services:
  backend:
    build:
      context: . # Path to the backend directory containing the Dockerfile
    ports:
      - "4000:4000" # Maps port 4000 on host to port 4000 in the container
    environment:
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_USER: root
      DB_PASSWORD: Psd@1234
      DB_NAME: criticsworld
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Psd@1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433" # Maps port 1433 on host to port 1433 in the container
